#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

systemctl try-restart "${MODULE_ID}.service"