#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent
import subprocess

host = subprocess.run(['hostname', '-f'], text=True, capture_output=True).stdout.strip()
# Prepare return variable
config = {}

# Read current configuration from the environment file
config["path"] = os.environ["TRAEFIK_PATH"]
config["fqdn"] = host

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
