#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Read current configuration from the environment file
config["path"] = os.environ["TRAEFIK_PATH"]
config["fqdn"] = agent.get_hostname()

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
